/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TextColorType, TextSizeType, TextVariantType } from "./common/types";
import { Book, LastPlayedGame } from "../common/api-data";
import { RichTextField } from "@prismicio/client";
export { TextColorType, TextSizeType, TextVariantType } from "./common/types";
export { Book, LastPlayedGame } from "../common/api-data";
export { RichTextField } from "@prismicio/client";
export namespace Components {
    interface AppButton {
        "buttonStyle"?: { [key: string]: any };
        "secondary"?: boolean;
    }
    interface AppHome {
    }
    interface AppImage {
        "alt"?: string;
        "height"?: number | string;
        "imgStyle"?: { [key: string]: any };
        "src": string;
        "width"?: number | string;
    }
    interface AppLayout {
    }
    interface AppPersonal {
    }
    interface AppRoot {
    }
    interface AppText {
        "blockEl"?: boolean;
        "color"?: TextColorType;
        "size"?: TextSizeType;
        "variant"?: TextVariantType;
    }
    interface BookShelf {
    }
    interface BookshelfBook {
        "book": Book;
    }
    interface BookshelfSection {
        "books": Book[];
        "halfSize": boolean;
        "sectionTitle": string;
    }
    interface CaseStudies {
    }
    interface ContentBox {
        "gutter"?: boolean;
        "helperText"?: string;
        "titleText"?: string;
    }
    interface GameCard {
        "game": LastPlayedGame;
    }
    interface LastPlayedSong {
    }
    interface MsCharCard {
    }
    interface RichTextRenderer {
        "field": RichTextField;
    }
}
declare global {
    interface HTMLAppButtonElement extends Components.AppButton, HTMLStencilElement {
    }
    var HTMLAppButtonElement: {
        prototype: HTMLAppButtonElement;
        new (): HTMLAppButtonElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppImageElement extends Components.AppImage, HTMLStencilElement {
    }
    var HTMLAppImageElement: {
        prototype: HTMLAppImageElement;
        new (): HTMLAppImageElement;
    };
    interface HTMLAppLayoutElement extends Components.AppLayout, HTMLStencilElement {
    }
    var HTMLAppLayoutElement: {
        prototype: HTMLAppLayoutElement;
        new (): HTMLAppLayoutElement;
    };
    interface HTMLAppPersonalElement extends Components.AppPersonal, HTMLStencilElement {
    }
    var HTMLAppPersonalElement: {
        prototype: HTMLAppPersonalElement;
        new (): HTMLAppPersonalElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTextElement extends Components.AppText, HTMLStencilElement {
    }
    var HTMLAppTextElement: {
        prototype: HTMLAppTextElement;
        new (): HTMLAppTextElement;
    };
    interface HTMLBookShelfElement extends Components.BookShelf, HTMLStencilElement {
    }
    var HTMLBookShelfElement: {
        prototype: HTMLBookShelfElement;
        new (): HTMLBookShelfElement;
    };
    interface HTMLBookshelfBookElement extends Components.BookshelfBook, HTMLStencilElement {
    }
    var HTMLBookshelfBookElement: {
        prototype: HTMLBookshelfBookElement;
        new (): HTMLBookshelfBookElement;
    };
    interface HTMLBookshelfSectionElement extends Components.BookshelfSection, HTMLStencilElement {
    }
    var HTMLBookshelfSectionElement: {
        prototype: HTMLBookshelfSectionElement;
        new (): HTMLBookshelfSectionElement;
    };
    interface HTMLCaseStudiesElement extends Components.CaseStudies, HTMLStencilElement {
    }
    var HTMLCaseStudiesElement: {
        prototype: HTMLCaseStudiesElement;
        new (): HTMLCaseStudiesElement;
    };
    interface HTMLContentBoxElement extends Components.ContentBox, HTMLStencilElement {
    }
    var HTMLContentBoxElement: {
        prototype: HTMLContentBoxElement;
        new (): HTMLContentBoxElement;
    };
    interface HTMLGameCardElement extends Components.GameCard, HTMLStencilElement {
    }
    var HTMLGameCardElement: {
        prototype: HTMLGameCardElement;
        new (): HTMLGameCardElement;
    };
    interface HTMLLastPlayedSongElement extends Components.LastPlayedSong, HTMLStencilElement {
    }
    var HTMLLastPlayedSongElement: {
        prototype: HTMLLastPlayedSongElement;
        new (): HTMLLastPlayedSongElement;
    };
    interface HTMLMsCharCardElement extends Components.MsCharCard, HTMLStencilElement {
    }
    var HTMLMsCharCardElement: {
        prototype: HTMLMsCharCardElement;
        new (): HTMLMsCharCardElement;
    };
    interface HTMLRichTextRendererElement extends Components.RichTextRenderer, HTMLStencilElement {
    }
    var HTMLRichTextRendererElement: {
        prototype: HTMLRichTextRendererElement;
        new (): HTMLRichTextRendererElement;
    };
    interface HTMLElementTagNameMap {
        "app-button": HTMLAppButtonElement;
        "app-home": HTMLAppHomeElement;
        "app-image": HTMLAppImageElement;
        "app-layout": HTMLAppLayoutElement;
        "app-personal": HTMLAppPersonalElement;
        "app-root": HTMLAppRootElement;
        "app-text": HTMLAppTextElement;
        "book-shelf": HTMLBookShelfElement;
        "bookshelf-book": HTMLBookshelfBookElement;
        "bookshelf-section": HTMLBookshelfSectionElement;
        "case-studies": HTMLCaseStudiesElement;
        "content-box": HTMLContentBoxElement;
        "game-card": HTMLGameCardElement;
        "last-played-song": HTMLLastPlayedSongElement;
        "ms-char-card": HTMLMsCharCardElement;
        "rich-text-renderer": HTMLRichTextRendererElement;
    }
}
declare namespace LocalJSX {
    interface AppButton {
        "buttonStyle"?: { [key: string]: any };
        "secondary"?: boolean;
    }
    interface AppHome {
    }
    interface AppImage {
        "alt"?: string;
        "height"?: number | string;
        "imgStyle"?: { [key: string]: any };
        "src"?: string;
        "width"?: number | string;
    }
    interface AppLayout {
    }
    interface AppPersonal {
    }
    interface AppRoot {
    }
    interface AppText {
        "blockEl"?: boolean;
        "color"?: TextColorType;
        "size"?: TextSizeType;
        "variant"?: TextVariantType;
    }
    interface BookShelf {
    }
    interface BookshelfBook {
        "book"?: Book;
    }
    interface BookshelfSection {
        "books"?: Book[];
        "halfSize"?: boolean;
        "sectionTitle"?: string;
    }
    interface CaseStudies {
    }
    interface ContentBox {
        "gutter"?: boolean;
        "helperText"?: string;
        "titleText"?: string;
    }
    interface GameCard {
        "game"?: LastPlayedGame;
    }
    interface LastPlayedSong {
    }
    interface MsCharCard {
    }
    interface RichTextRenderer {
        "field"?: RichTextField;
    }
    interface IntrinsicElements {
        "app-button": AppButton;
        "app-home": AppHome;
        "app-image": AppImage;
        "app-layout": AppLayout;
        "app-personal": AppPersonal;
        "app-root": AppRoot;
        "app-text": AppText;
        "book-shelf": BookShelf;
        "bookshelf-book": BookshelfBook;
        "bookshelf-section": BookshelfSection;
        "case-studies": CaseStudies;
        "content-box": ContentBox;
        "game-card": GameCard;
        "last-played-song": LastPlayedSong;
        "ms-char-card": MsCharCard;
        "rich-text-renderer": RichTextRenderer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-button": LocalJSX.AppButton & JSXBase.HTMLAttributes<HTMLAppButtonElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-image": LocalJSX.AppImage & JSXBase.HTMLAttributes<HTMLAppImageElement>;
            "app-layout": LocalJSX.AppLayout & JSXBase.HTMLAttributes<HTMLAppLayoutElement>;
            "app-personal": LocalJSX.AppPersonal & JSXBase.HTMLAttributes<HTMLAppPersonalElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-text": LocalJSX.AppText & JSXBase.HTMLAttributes<HTMLAppTextElement>;
            "book-shelf": LocalJSX.BookShelf & JSXBase.HTMLAttributes<HTMLBookShelfElement>;
            "bookshelf-book": LocalJSX.BookshelfBook & JSXBase.HTMLAttributes<HTMLBookshelfBookElement>;
            "bookshelf-section": LocalJSX.BookshelfSection & JSXBase.HTMLAttributes<HTMLBookshelfSectionElement>;
            "case-studies": LocalJSX.CaseStudies & JSXBase.HTMLAttributes<HTMLCaseStudiesElement>;
            "content-box": LocalJSX.ContentBox & JSXBase.HTMLAttributes<HTMLContentBoxElement>;
            "game-card": LocalJSX.GameCard & JSXBase.HTMLAttributes<HTMLGameCardElement>;
            "last-played-song": LocalJSX.LastPlayedSong & JSXBase.HTMLAttributes<HTMLLastPlayedSongElement>;
            "ms-char-card": LocalJSX.MsCharCard & JSXBase.HTMLAttributes<HTMLMsCharCardElement>;
            "rich-text-renderer": LocalJSX.RichTextRenderer & JSXBase.HTMLAttributes<HTMLRichTextRendererElement>;
        }
    }
}
