/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TextColorType, TextSizeType, TextVariantType } from "./common/types";
import { RichTextField } from "@prismicio/client";
export { TextColorType, TextSizeType, TextVariantType } from "./common/types";
export { RichTextField } from "@prismicio/client";
export namespace Components {
    interface AppButton {
        "buttonStyle"?: { [key: string]: any };
    }
    interface AppHome {
    }
    interface AppImage {
        "alt"?: string;
        "height"?: number;
        "imgStyle"?: { [key: string]: any };
        "objectFit"?: 'cover' | 'contain';
        "src": string;
        "width"?: number;
    }
    interface AppLayout {
    }
    interface AppRoot {
    }
    interface AppText {
        "blockEl"?: boolean;
        "color"?: TextColorType;
        "size"?: TextSizeType;
        "variant"?: TextVariantType;
    }
    interface CaseStudies {
    }
    interface ContentBox {
        "gutter"?: boolean;
        "titleText"?: string;
    }
    interface LastPlayedSong {
    }
    interface MsCharCard {
    }
    interface RichTextRenderer {
        "field": RichTextField;
    }
    interface UnwindZone {
    }
}
declare global {
    interface HTMLAppButtonElement extends Components.AppButton, HTMLStencilElement {
    }
    var HTMLAppButtonElement: {
        prototype: HTMLAppButtonElement;
        new (): HTMLAppButtonElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppImageElement extends Components.AppImage, HTMLStencilElement {
    }
    var HTMLAppImageElement: {
        prototype: HTMLAppImageElement;
        new (): HTMLAppImageElement;
    };
    interface HTMLAppLayoutElement extends Components.AppLayout, HTMLStencilElement {
    }
    var HTMLAppLayoutElement: {
        prototype: HTMLAppLayoutElement;
        new (): HTMLAppLayoutElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTextElement extends Components.AppText, HTMLStencilElement {
    }
    var HTMLAppTextElement: {
        prototype: HTMLAppTextElement;
        new (): HTMLAppTextElement;
    };
    interface HTMLCaseStudiesElement extends Components.CaseStudies, HTMLStencilElement {
    }
    var HTMLCaseStudiesElement: {
        prototype: HTMLCaseStudiesElement;
        new (): HTMLCaseStudiesElement;
    };
    interface HTMLContentBoxElement extends Components.ContentBox, HTMLStencilElement {
    }
    var HTMLContentBoxElement: {
        prototype: HTMLContentBoxElement;
        new (): HTMLContentBoxElement;
    };
    interface HTMLLastPlayedSongElement extends Components.LastPlayedSong, HTMLStencilElement {
    }
    var HTMLLastPlayedSongElement: {
        prototype: HTMLLastPlayedSongElement;
        new (): HTMLLastPlayedSongElement;
    };
    interface HTMLMsCharCardElement extends Components.MsCharCard, HTMLStencilElement {
    }
    var HTMLMsCharCardElement: {
        prototype: HTMLMsCharCardElement;
        new (): HTMLMsCharCardElement;
    };
    interface HTMLRichTextRendererElement extends Components.RichTextRenderer, HTMLStencilElement {
    }
    var HTMLRichTextRendererElement: {
        prototype: HTMLRichTextRendererElement;
        new (): HTMLRichTextRendererElement;
    };
    interface HTMLUnwindZoneElement extends Components.UnwindZone, HTMLStencilElement {
    }
    var HTMLUnwindZoneElement: {
        prototype: HTMLUnwindZoneElement;
        new (): HTMLUnwindZoneElement;
    };
    interface HTMLElementTagNameMap {
        "app-button": HTMLAppButtonElement;
        "app-home": HTMLAppHomeElement;
        "app-image": HTMLAppImageElement;
        "app-layout": HTMLAppLayoutElement;
        "app-root": HTMLAppRootElement;
        "app-text": HTMLAppTextElement;
        "case-studies": HTMLCaseStudiesElement;
        "content-box": HTMLContentBoxElement;
        "last-played-song": HTMLLastPlayedSongElement;
        "ms-char-card": HTMLMsCharCardElement;
        "rich-text-renderer": HTMLRichTextRendererElement;
        "unwind-zone": HTMLUnwindZoneElement;
    }
}
declare namespace LocalJSX {
    interface AppButton {
        "buttonStyle"?: { [key: string]: any };
    }
    interface AppHome {
    }
    interface AppImage {
        "alt"?: string;
        "height"?: number;
        "imgStyle"?: { [key: string]: any };
        "objectFit"?: 'cover' | 'contain';
        "src"?: string;
        "width"?: number;
    }
    interface AppLayout {
    }
    interface AppRoot {
    }
    interface AppText {
        "blockEl"?: boolean;
        "color"?: TextColorType;
        "size"?: TextSizeType;
        "variant"?: TextVariantType;
    }
    interface CaseStudies {
    }
    interface ContentBox {
        "gutter"?: boolean;
        "titleText"?: string;
    }
    interface LastPlayedSong {
    }
    interface MsCharCard {
    }
    interface RichTextRenderer {
        "field"?: RichTextField;
    }
    interface UnwindZone {
    }
    interface IntrinsicElements {
        "app-button": AppButton;
        "app-home": AppHome;
        "app-image": AppImage;
        "app-layout": AppLayout;
        "app-root": AppRoot;
        "app-text": AppText;
        "case-studies": CaseStudies;
        "content-box": ContentBox;
        "last-played-song": LastPlayedSong;
        "ms-char-card": MsCharCard;
        "rich-text-renderer": RichTextRenderer;
        "unwind-zone": UnwindZone;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-button": LocalJSX.AppButton & JSXBase.HTMLAttributes<HTMLAppButtonElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-image": LocalJSX.AppImage & JSXBase.HTMLAttributes<HTMLAppImageElement>;
            "app-layout": LocalJSX.AppLayout & JSXBase.HTMLAttributes<HTMLAppLayoutElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-text": LocalJSX.AppText & JSXBase.HTMLAttributes<HTMLAppTextElement>;
            "case-studies": LocalJSX.CaseStudies & JSXBase.HTMLAttributes<HTMLCaseStudiesElement>;
            "content-box": LocalJSX.ContentBox & JSXBase.HTMLAttributes<HTMLContentBoxElement>;
            "last-played-song": LocalJSX.LastPlayedSong & JSXBase.HTMLAttributes<HTMLLastPlayedSongElement>;
            "ms-char-card": LocalJSX.MsCharCard & JSXBase.HTMLAttributes<HTMLMsCharCardElement>;
            "rich-text-renderer": LocalJSX.RichTextRenderer & JSXBase.HTMLAttributes<HTMLRichTextRendererElement>;
            "unwind-zone": LocalJSX.UnwindZone & JSXBase.HTMLAttributes<HTMLUnwindZoneElement>;
        }
    }
}
